---
header-includes:
- \usepackage{booktabs}
- \usepackage{makecell}
- \usepackage{longtable}
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    toc: TRUE
    toc_depth: 2
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
    dev: png
    keep_md: yes
  pdf_document:
    toc: TRUE
    toc_depth: 4
    dev: png
    extra_dependencies: ["float"]
    keep_md: yes
urlcolor: blue
geometry: "left=3cm,right=3cm"
params:
  managedarea: ma,
  p_inc: included_params,
  a_inc: included_acts,
  d_inc: included_depths
title: '`r paste(ma)`'
subtitle: '`r paste("SEACAR Discrete Water Quality Analysis")`'
tables: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(
   warning=FALSE,
   message=FALSE,
   echo=FALSE,
   dpi=200
)
options(knitr.kable.NA = '-')

```



```{r libraries, message=FALSE, echo=FALSE, warning=FALSE, include=FALSE}
library(knitr)
library(data.table)
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggpubr)
library(scales)
library(EnvStats)
library(tidyr)
library(kableExtra)
library(glue)
library(grid)
options(scipen=999)

# Set height and width for plot outputs (.png outputs only)
h <- 891
w <- 1600

# Set color palette for sig and non-sig trendlines
sig_color <- "#000099"
nonsig_color <- "#900667"

```

\newpage
# Indicators


``` {r continuous_dataframe_setup}

# Full parameter names and units
# Create dataframe containing that info so that 
# full data file doesn't have to load each time
cont_params_long <- c("Dissolved Oxygen","Dissolved Oxygen Saturation","pH",
                      "Salinity","Turbidity","Water Temperature")
cont_params_short <- c("DO","DOS","pH","Sal","Turb","TempW")
cont_param_units <- c("mg/L","%","pH","ppt","NTU","Degrees C")
cont_regions <- c("NE","NW","SE","SW")

cont_param_df <- data.table(param_short = cont_params_short,
                            parameter = cont_params_long,
                            unit = cont_param_units)

```


```{r x-axis_breaks_function}

breaks <- function(plot_data, type="Discrete", ret="break"){
  if(type=="Discrete"){
    #Determine max and min time (Year) for plot x-axis
    t_min <- min(plot_data$Year)
    t_max <- max(plot_data$YearMonthDec)
    t_max_brk <- as.integer(round(t_max, 0))
    t <- t_max-t_min
  
    # Sets break intervals based on the number of years spanned by data
    if(t>=30){
      brk <- -10
    }else if(t<30 & t>=10){
      brk <- -4
    }else if(t<10){
      brk <- -1
    }
  }
  
  if(type=="Continuous"){
    #Determine max and min time (Year) for plot x-axis
    t_min <- min(plot_data$Year)
    t_max <- max(plot_data$YearMonthDec)
    t_max_brk <- as.integer(round(t_max, 0))
    t <- t_max-t_min
    min_RV <- min(plot_data$Mean)
    
    # Creates break intervals for plots based on number of years of data
    if(t>=30){
      # Set breaks to every 10 years if more than 30 years of data
      brk <- -10
    }else if(t<30 & t>=10){
      # Set breaks to every 4 years if between 30 and 10 years of data
      brk <- -4
    }else if(t<10 & t>=4){
      # Set breaks to every 2 years if between 10 and 4 years of data
      brk <- -2
    }else if(t<4 & t>=2){
      # Set breaks to every year if between 4 and 2 years of data
      brk <- -1
    }else if(t<2){
      # Set breaks to every year if less than 2 years of data
      brk <- -1
      # Sets t_max to be 1 year greater and t_min to be 1 year lower
      # Forces graph to have at least 3 tick marks
      t_max <- t_max+1
      t_min <- t_min-1
    }
  }
  
  if(ret=="break"){
    return(seq(t_max_brk, t_min, brk))
  }
  
  if(ret=="lims"){
    return(c(t_min-0.25, t_max+0.25))
  }
}

```


```{r SKT_Trendlines_ManagedArea Function}

plot_trendlines <- function(p, a, d, activity_label, depth_label, y_labels, parameter, skt_data, discrete_data) {
  
  skt_stats <- skt_data[ParameterName==parameter & RelativeDepth==d & ActivityType==a, ]
  
  data <- discrete_data[ParameterName==parameter & Include, ]
  
  if(!a=="All"){
    # Filter for desired ActivityType, ensuring they plot correctly as Lab or Field (Not 'Field Msr/Obs.' etc)
    data <- data[str_detect(ActivityType, a), ]
    data$ActivityType <- a
  }
  
  data[, Mean := mean(ResultValue, na.rm = TRUE), by = .(Year, Month)]
  
  ### SKT STATS ###
  # Gets x and y values for starting point for trendline
  KT.Plot <- skt_stats %>%
    group_by(ManagedAreaName) %>%
    summarize(start_x=decimal_date(EarliestSampleDate),
              start_y=(start_x-EarliestYear)*SennSlope+SennIntercept,
              end_x=decimal_date(LastSampleDate),
              end_y=(end_x-EarliestYear)*SennSlope+SennIntercept,
              p = unique(p))
  KT.Plot <- as.data.table(KT.Plot[order(KT.Plot$ManagedAreaName), ])
  KT.Plot <- KT.Plot[!is.na(KT.Plot$end_y),]
  KT.Plot <- KT.Plot[!is.na(KT.Plot$start_y),] 
  setDT(KT.Plot)
  
  if (nrow(data) == 0) {
    invisible()
    # print("error")
  } else {
    
    cat("  \n")
    cat(glue("### {parameter} - {type}"))
    cat("  \n")
    
    # Gets data to be used in plot for managed area
    plot_data <- merge(data, KT.Plot, by=c("ManagedAreaName"), all=TRUE)
    plot_data[, `:=` (sig = ifelse(p<=0.05, "Significant Trend", "Non-significant Trend"))]

    # Create plot object with data and trendline
    p1 <- ggplot(data=plot_data,
                 aes(x=YearMonthDec, y=Mean)) +
      # geom_line(size=0.75, color="#333333", alpha=0.6) +
      geom_point(aes(shape=plot_data$ActivityType), size=3, color="#333333", fill="#cccccc",
                 alpha=0.75) +
      geom_segment(aes(x = start_x, y = start_y, xend = end_x, yend = end_y, 
                       color = sig),
                   linewidth = 1.2, alpha = 0.7, show.legend = TRUE) +
      labs(title=paste0(parameter," - Discrete, ", depth_label),
           subtitle=ma,
           x="Year", y=y_labels) +
      scale_x_continuous(limits=breaks(plot_data, type="Discrete", ret="lims"),
                         breaks=breaks(plot_data, type="Discrete", ret="break")) +
      scale_shape_manual(values = c("Field"=21,"Lab"=24), 
                         name = "Data type") +
      scale_color_manual(name = "Trend type", 
                         values = c("Significant Trend" = sig_color,
                                    "Non-significant Trend" = nonsig_color)) +
      plot_theme
    
    # Creates ResultTable to display statistics below plot
    ResultTable <- skt_stats %>%
      select(ActivityType, "Statistical Trend", N_Data, N_Years, "Period of Record", 
             Median, tau, SennIntercept, SennSlope, p) # %>%
      # rename("Activity Type" = ActivityType,
      #        "Sample Count" = N_Data,
      #        "Years with Data" = N_Years,
      #        "Median Result Value" = Median,
      #        "Tau" = tau, "Sen Intercept" = SennIntercept, "Sen Slope" = SennSlope, "P" = p)
    names(ResultTable) <- gsub("_", "-", names(ResultTable))
    
    print(p1)
    
    ggsave(filename = paste0("output/WQ_Discrete/", ma_short, "_", 
                             gsub(",","",(gsub(" ","_",parameter))), ".png"),
           plot = p1, width = w, height = h, units = "px", dpi = 300,
           scale = 1)
    
    result_table <- kable(ResultTable, format="latex",
                          caption=paste0("Seasonal Kendall-Tau Results for - ", parameter),
                          row.names = FALSE, digits = 5,
                          booktabs = T, linesep = "", escape = F, longtable = F) %>%
      kable_styling(latex_options = c("scale_down", "HOLD_position"), 
                    position = "center")

    cat("  \n")
    print(result_table)
    cat("\n \n \n")
    
    # Add extra space at the end to prevent the next figure from being too
    # close.
    cat("\n \n \n")
    rm(plot_data)
    rm(MA_YM_Stats)
    # rm(KT.Plot)
    rm(skt_stats)
  }
}

```


```{r SKT_Trendlines Continuous Function}

plot_trendlines_cont_combined <- function(ma, cont_plot_data, param, y_labels, parameter){
  
  data <- cont_plot_data[ManagedAreaName==ma & ParameterName==parameter, ]
  
  if(length(unique(data$ProgramLocationID))>0){
    cat("  \n")
    cat(glue("### {parameter} - {type}"))
    cat("  \n")
    
    # Account for managed areas with large number of continuous sites
    # Too many to plot together, plot combined by Program
    if(length(unique(data$ProgramLocationID))>10){
      
      for(pid in unique(data$ProgramID)){
        # all plots together for a given ProgramID
        plot_data <- setDT(data[ProgramID==pid, ])
        
        # Program Name
        p_name <- unique(plot_data$ProgramName)
        # number of stations for shape-palette
        n <- length(unique(plot_data$ProgramLocationID))
        # Array of shape values, account for missing ggplot shape values 26-32
        shapes <- c(21,22,23,24,25,seq(1:(n-5)))
        
        p1 <- ggplot(data = plot_data, aes(x = YearMonthDec, y = Mean, group = factor(ProgramLocationID))) +
          geom_point(aes(shape = ProgramLocationID), color = "#444444", fill = "#cccccc", size = 3, alpha = 0.9, show.legend = TRUE) +
          geom_segment(aes(x = start_x, y = start_y, xend = end_x, yend = end_y, 
                           linetype = ProgramLocationID, color = ProgramLocationID),
                       linewidth = 1.2, alpha = 0.7, show.legend = TRUE) +
          labs(title = paste0(ma, "\n", p_name, "\nProgramID: ", pid),
               subtitle = paste0(parameter, " - Continuous"),
               x = "Year", y = y_labels) +
          scale_x_continuous(limits = breaks(plot_data, type = "Continuous", ret = "lims"),
                             breaks = breaks(plot_data, type = "Continuous", ret = "break")) +
          scale_shape_manual(values = shapes) +
          scale_linetype_manual(values = 1:n) +
          scale_color_manual(values = 1:n) + 
          labs(shape = "Program location", linetype = "Program location", color = "Program location") + 
          plot_theme +
          theme(legend.text = element_text(size = 7))
        
        ResultTable <- skt_stats %>%
          filter(ProgramID==pid) %>%
          select(ProgramLocationID, "Statistical Trend", N_Data, N_Years, "Period of Record", Median, tau,
                 SennIntercept, SennSlope, p) %>%
          mutate_if(is.numeric, ~round(., 2)) # %>%
        # rename("Program Location" = ProgramLocationID, "Sample Count" = N_Data,
        #        "Years with Data" = N_Years, "Median Result Value" = Median,
        #        "Tau" = tau, "Sen Intercept" = SennIntercept, "Sen Slope" = SennSlope, "P" = p)
        
        # Remove text-based "NA" values in p column
        if (nrow(ResultTable[ResultTable$p=="    NA", ]) > 0){
          ResultTable[ResultTable$p=="    NA", ]$p <- "-"
        }
        ResultTable[is.na(ResultTable)] <- "-"
        
        # t1 <- ggtexttable(ResultTable, rows=NULL,
        #                   theme=ttheme(base_size=10)) %>%
        #   tab_add_footnote(text="p < 0.00005 appear as 0 due to rounding.\n
        #                           SennIntercept is intercept value at beginning of
        #                           record for monitoring location",
        #                    size=10, face="italic")
        
        # title <- glue("#### {p_name}: ({pid})")
        # cat("  \n")
        # cat(title)
        cat("    \n")
        cat("  \n")
        cat("  \n")
        # plot <- ggarrange(p1, t1, ncol=1, heights=c(0.71, 0.29))
        print(p1)
        
        # save fig
        ggsave(filename = paste0("output/WQ_Continuous/", ma_short, "_", 
                                 gsub(",","",(gsub(" ","_",parameter))), "_", pid, 
                                 ".png"),
               plot = p1, width = w, height = h, units = "px", dpi = 300,
               scale = 1)
        
        cat("  \n")
        
        names(ResultTable) <- gsub("_", "-", names(ResultTable))
        
        result_table <- kable(ResultTable, format="latex",
                              caption=paste0("Seasonal Kendall-Tau Results for All Stations - ", parameter),
                              row.names = FALSE, digits = 5,
                              booktabs = T, linesep = "", escape = F, longtable = F) %>%
          kable_styling(latex_options = c("scale_down", "HOLD_position"), position = "center")
        
        print(result_table)
        cat("\n \n \n")
      }
    } else {
      # all plots together
      plot_data <- setDT(data)
      
      # number of stations for shape-palette
      n <- length(unique(plot_data$ProgramLocationID))
      shapes <- c(21,22,23,24,25,seq(1:(n-5)))
      
      p1 <- ggplot(data=plot_data, aes(x=YearMonthDec, y=Mean, group=factor(ProgramLocationID))) +
        geom_point(aes(shape=ProgramLocationID), color="#444444" ,fill="#cccccc", size=3,alpha=0.9, show.legend = TRUE) +
        geom_segment(aes(x = start_x, y = start_y, xend = end_x, yend = end_y, 
                         color = sig, linetype=ProgramLocationID),
                     linewidth = 1.2, alpha = 0.7, show.legend = TRUE) +
        labs(title=paste0(ma, "\nAll Stations"),
             subtitle=paste0(parameter, " - Continuous"),
             x="Year", y=y_labels) +
        scale_x_continuous(limits=breaks(plot_data, type="Continuous", ret="lims"),
                           breaks=breaks(plot_data, type="Continuous", ret="break")) +
        plot_theme + 
        scale_shape_manual(values=shapes, name = "Program location") +
        scale_color_manual(values = c("Significant Trend" = "#000099","Non-significant Trend" = "#900667")) +
        labs(shape  = "Program location", linetype = "Program location", colour = "Trend type")
      
      ResultTable <- skt_stats %>%
        select(ProgramLocationID, "Statistical Trend", N_Data, N_Years, "Period of Record", Median, tau,
               SennIntercept, SennSlope, p) %>%
        mutate_if(is.numeric, ~round(., 2)) # %>%
      # rename("Program Location" = ProgramLocationID, "Sample Count" = N_Data,
      #        "Years with Data" = N_Years, "Median Result Value" = Median,
      #        "Tau" = tau, "Sen Intercept" = SennIntercept, "Sen Slope" = SennSlope, "P" = p)
      
      # Remove text-based "NA" values in p column
      if (nrow(ResultTable[ResultTable$p=="    NA", ]) > 0){
        ResultTable[ResultTable$p=="    NA", ]$p <- "-"
      }
      ResultTable[is.na(ResultTable)] <- "-"
      
      # t1 <- ggtexttable(ResultTable, rows=NULL,
      #                   theme=ttheme(base_size=10)) %>%
      #   tab_add_footnote(text="p < 0.00005 appear as 0 due to rounding.\n
      #                           SennIntercept is intercept value at beginning of
      #                           record for monitoring location",
      #                    size=10, face="italic")
      
      cat("  \n")
      # plot <- ggarrange(p1, t1, ncol=1, heights=c(0.71, 0.29))
      print(p1)
      
      # save fig
      ggsave(filename = paste0("output/WQ_Continuous/", ma_short, "_", 
                               gsub(",","",(gsub(" ","_",parameter))), ".png"),
             plot = p1, width = w, height = h, units = "px", dpi = 300,
             scale = 1)
      
      cat("  \n")
      
      names(ResultTable) <- gsub("_", "-", names(ResultTable))
      
      result_table <- kable(ResultTable, format="latex",
                            caption=paste0("Seasonal Kendall-Tau Results for All Stations - ", parameter),
                            row.names = FALSE, digits = 5,
                            booktabs = T, linesep = "", escape = F, longtable = F) %>%
        kable_styling(latex_options = c("scale_down", "HOLD_position"), position = "center")
      
      print(result_table)
      cat("\n \n \n")    
    }
  }
  
}

```


```{r Plotting, warning=FALSE, fig.height=5, fig.width=10, results="asis"}

for(indicator in unique(websiteParams$IndicatorName)){
  cat("  \n")
  cat(glue("## {indicator}"))
  cat("  \n")
  
  # Filter once for the current indicator
  indicator_subset <- websiteParams[IndicatorName == indicator, ]
  
  for(i in 1:nrow(indicator_subset)){
    filteredSubset <- indicator_subset[i]
    parameter <- filteredSubset$ParameterName
    param_short <- filteredSubset$ParameterShort
    unit <- filteredSubset$ParameterUnits
    type <- filteredSubset$SamplingFrequency
    activity <- filteredSubset$ActivityType
    depth <- filteredSubset$RelativeDepth
    
    # Define y-label, activity-label, depth-label for plot labels
    y_labels <- ifelse(parameter == "pH", parameter, paste0(parameter, " (" , unit, ")"))
    activity_label <- ifelse(activity=="All", "Lab and Field Combined", activity)
    depth_label <- ifelse(depth=="All", "All Depths", "Surface")
    
    if(type=="Continuous"){
      plot_trendlines_cont_combined(ma = ma, cont_plot_data = cont_plot_data, param = param_short, y_labels = y_labels, parameter = parameter)
    }
    
    if(type=="Discrete"){
      plot_trendlines(param_short, activity, depth, activity_label, depth_label, 
                      y_labels, parameter, skt_data, discrete_data)
    }
  }
}

```

