# Water Column

The water column habitat extends from the water’s surface to the bottom sediments, and it’s where fish, dolphins, crabs and people swim! So much life makes its home in the water column that the health of marine and coastal ecosystems, as well as human economies, depend on the condition of this vulnerable habitat. Local patterns of rainfall, temperature, winds and currents can rapidly change the condition of the water column, while global influences such as [El Niño/La Niña](https://oceanservice.noaa.gov/facts/ninonina.html), large-scale fluctuation in sea temperatures and climate change can have long-term effects. Inputs from the prosperity of our day-to-day lives including farming, mining and forestry, and emissions from power generation, automobiles and water treatment can also alter the health of the water column. Acting alone or together, each input can have complex and lasting effects on habitats and ecosystems.

\
SEACAR evaluates water column health with several essential parameters. These include nutrient surveys of nitrogen and phosphorus, and water quality assessments of salinity, dissolved oxygen, pH, and water temperature. Water clarity is evaluated with Secchi depth, turbidity, levels of chlorophyll a, total suspended solids, and colored dissolved organic matter. Additionally, the richness of nekton is indicated by the abundance of free-swimming fishes and macroinvertebrates like crabs and shrimps.

# Seasonal Kendall-Tau Analysis

Indicators must have a minimum of five to ten years, depending on the habitat, of data within the geographic range of the analysis to be included in the analysis. Ten years of data are required for discrete parameters, and five years of data are required for continuous parameters. If there are insufficient years of data, the number of years of data available will be noted and labeled as "insufficient data to conduct analysis". Further, for the preferred Seasonal Kendall-Tau test, there must be data from at least two months in common across at least two consecutive years within the RCP managed area being analyzed. Values that pass both of these tests will be included in the analysis and be labeled as *Use_In_Analysis* = **TRUE**. Any that fail either test will be excluded from the analyses and labeled as *Use_In_Analysis* = **FALSE**. The points for all Water Column plots displayed in this section are monthly averages. Trend significance will be denoted as "Significant Trend" (when p \< 0.05), or "Non-significant Trend" (when p \>= 0.05). Any parameters with insufficient data to perform Seasonal Kendall-Tau test will have their monthly averages plotted without a corresponding trend line.
