---
title: "Big Bend Seagrasses Aquatic Preserve"
subtitle: "Seagrass and Water Quality Trend Analysis"
author: "Florida SEACAR"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: TRUE
    toc_depth: 4
    dev: png
    extra_dependencies: ["longtable", "float", "booktabs"]
    keep_md: yes
    fig_crop: no
    fig_caption: no
    keep_tex: true
    includes:
      in_header: "preamble.tex"
urlcolor: blue
geometry: margin=0.75in
bibliography: "SEACAR DDI citations2.bib"
csl: "nature.csl"
---

```{r setup, include=FALSE}
library(patchwork)
library(knitcitations)
# Citation set up
knitcitations::cleanbib()
options("citation_format" = "pandoc",
        "cite.style" = "numeric")

# Load in bibliography
bib <- read.bibtex("SEACAR DDI citations.bib")
# Categorize each program ID as "cited" without explicitly displaying in report
# for(prog in all_prog_ids){
#   cat(knitcitations::citep(bib[[paste0("SEACARID", prog)]]))
# }

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  dpi=200,
  fig.pos = 'p')

# Function to allow dynamic plot sizes
subchunkify <- SEACAR::subchunkify

# Custom SEACAR palette
seacar_palette <- SEACAR::seacar_palette2

seacar_sp_palette <- c("#005396","#0088B1","#00ADAE","#65CCB3","#AEE4C1",
                       "#FDEBA8","#F8CD6D","#F5A800","#F17B00")

# SEACAR Theme
plot_theme <- SEACAR::SEACAR_plot_theme()

```


```{r general_functions}

# Makes NA into "-" in tables
options(knitr.kable.NA = "-")

# Function to return report-ready datatable format
make_kable <- function(data_table, table_caption, format="latex"){
  return(
    kbl(data_table,
        format=format,
        caption=table_caption,
        escape=F,
        digits=2,
        vline = "",
        linesep = "",
        longtable = F,
        booktabs = T) %>%
      kable_styling(latex_options = c("scale_down","HOLD_position",
                                      "striped"),
                    position = "center") %>%
      row_spec(0, italic = TRUE)
    )
}

```


```{r trendline_plot_functions}
# Seasonal Kendall-Tau plot function
plot_trendlines <- function(sys, param, activity_label, depth_label, y_labels){
  data <- data_combined %>% filter(System==sys)
  setDT(data)
  
  if (nrow(data) == 0) {
    invisible()
  } else {
    # Gets data to be used in plot for managed area
    plot_data <- data[ParameterName==param, ]
    plot_data[, `:=` (sig = ifelse(p<=0.05, "Significant Trend", "Non-significant Trend"))]
    plot_data$sig <- factor(plot_data$sig)
    
    #Determine max and min time (Year) for plot x-axis
    t_min <- min(plot_data$Year)
    t_max <- max(plot_data$YearMonthDec)
    t_max_brk <- as.integer(round(t_max, 0))
    t <- t_max-t_min
    min_RV <- min(plot_data$Mean)
    
    # Sets break intervals based on the number of years spanned by data
    if(t>=30){
      brk <- -10
    }else if(t<30 & t>=10){
      brk <- -4
    }else if(t<10 & t>=4){
      brk <- -2
    }else if(t<4 & t>=1){
      brk <- -1
    }else if(t<1){
      brk <- -1
      t_max <- round(t_max)
    }
    
    # Create plot object with data and trendline
    p1 <- ggplot(data=plot_data,
                 aes(x=YearMonthDec, y=Mean)) +
      # geom_line(size=0.75, color="#333333", alpha=0.6) +
      geom_point(aes(shape=plot_data$ActivityType), size=3, color="#333333", fill="#cccccc", alpha=0.75) +
      geom_segment(aes(x = start_x, y = start_y, xend = end_x, yend = end_y, color = sig), 
                   linewidth=1.2, alpha=0.7, show.legend = TRUE) +
      labs(title=paste0(param," - Discrete, ", depth_label),
           subtitle=paste0(sys, " - ", "Big Bend Seagrasses AP"),
           x="Year", y=y_labels) +
      scale_x_continuous(limits=c(t_min-0.25, t_max+0.25),
                         breaks=seq(t_max_brk, t_min, brk)) +
      scale_shape_manual(values = c("Field"=21,"Lab"=24), 
                         name = "Activity type") +
      scale_color_manual(name = "Trend type",
                         values = c("Significant Trend" = "#000099",
                                    "Non-significant Trend" = "#900667"),
                         limits = c("Significant Trend", "Non-significant Trend"),
                         na.translate = TRUE, drop = FALSE) +
      plot_theme +
      facet_wrap(~Type, dir="h") +
      guides(col = guide_legend(order = 1), 
             shape = guide_legend(order = 2, override.aes = list(linetype = NA)))
    
    # Creates ResultTable to display statistics below plot
    ResultTable <- skt_data_combined[System==sys & ParameterName==param, ] %>%
      select(Type, RelativeDepth, N_Data, N_Years, Median, Independent, tau, p,
             SennSlope, SennIntercept, ChiSquared, pChiSquared, Trend)
    # Create table object
    t1 <- ggtexttable(ResultTable, rows=NULL,
                      theme=ttheme(base_size=8)) %>%
                      tab_add_footnote(text="p < 0.00005 appear as 0 due to rounding.\n
                      SennIntercept is intercept value at beginning of
                      record for monitoring location",
                      size=10, face="italic")
    
    # Arrange and display plot and statistic table
    # plot <- ggarrange(p1, t1, ncol=1, heights=c(0.9, 0.1))
    plot <- (p1 / t1) + plot_layout(nrow=2, heights = c(3,1))
    print(plot)
    cat("  \n")
    cat("  \n")
    
    # Save file as .rds for use in dashboard
    plotName <- paste0("output/rds/plots/", sys, "_", type, "_", param, ".rds")
    saveRDS(plot, file=plotName)
  }
}

```


```{r map_functions}
# Prep WQ and SAV data by extracting coordinates and converting from sf dataframe
wq_map_data <- wq_data
wq_map_data$lon <- st_coordinates(wq_map_data)[,1]
wq_map_data$lat <- st_coordinates(wq_map_data)[,2]
wq_map_data <- wq_map_data %>% st_drop_geometry() %>%
  group_by(ProgramLocationID, ProgramID, ProgramName, System, Type, lon, lat) %>% reframe() %>% as.data.table()

sav_map_data <- sav_data
sav_map_data$lon <- st_coordinates(sav_map_data)[,1]
sav_map_data$lat <- st_coordinates(sav_map_data)[,2]
sav_map_data <- sav_map_data %>% st_drop_geometry() %>% as.data.table()

map <- function(type="SAV", output="all", sys){
  if(type=="SAV"){
    data <- sav_map_data
    # Set order for display on map (N to S)
    data <- data[order(factor(data$System, levels=c("St. Marks",
                                                    "Aucilla",
                                                    "Keaton Beach",
                                                    "Steinhatchee",
                                                    "Cedar Key")))]
    # map output filepath
    map_out <- "output/maps/sav.png"
  } else if(type=="WQ"){
    data <- wq_map_data
    # Set order for display on map (N to S)
    data <- data[order(factor(data$System, levels=c(c("St. Marks",
                                                      "Aucilla",
                                                      "Econfina",
                                                      "Keaton Beach",
                                                      "Steinhatchee",
                                                      "Horseshoe Beach",
                                                      "Suwannee",
                                                      "Cedar Key",
                                                      "Waccasassa"))))]
    # map output filepath
    map_out <- "output/maps/wq.png"
    typeMap_out <- "output/maps/wq_types.png"
    sysMap_out <- paste0("output/maps/",sys,"_map.png")
  }
  
  # Define palette
  pal <- colorFactor("plasma", levels = c("St. Marks",
                                          "Aucilla",
                                          "Econfina",
                                          "Keaton Beach",
                                          "Steinhatchee",
                                          "Horseshoe Beach",
                                          "Suwannee",
                                          "Cedar Key",
                                          "Waccasassa"))
  
  typePal <- colorFactor(c("#6FA1DD", "#964059"),
                         c("Estuary", "River"))
  
  # Calculate N_data for point sizes
  sys_data_info <- data %>%
    group_by(ProgramLocationID) %>%
    summarise(n_data = n()) %>%
    rename(ProgramLoc = ProgramLocationID)
  
  # Define radius
  rad <- ifelse(type=="SAV", sqrt(sys_data_info$n_data)/5, 3)
  
  data$System <- factor(data$System, levels = c("St. Marks",
                                                "Aucilla",
                                                "Econfina",
                                                "Keaton Beach",
                                                "Steinhatchee",
                                                "Horseshoe Beach",
                                                "Suwannee",
                                                "Cedar Key",
                                                "Waccasassa"))
  
  # Create leaflet map
  map <- leaflet(data, options = leafletOptions(zoomControl = FALSE)) %>%
    addProviderTiles(providers$CartoDB.PositronNoLabels) %>%
    addCircleMarkers(lat = ~lat, lng = ~lon, color=~pal(System), 
                     radius=rad, fillOpacity=0.3) %>%
    addLegend(pal=pal, values=~System, title="")
  
  if(type=="WQ"){
    # Create leaflet map with Type (Estuary vs River)
    map2 <- leaflet(data, options = leafletOptions(zoomControl = FALSE)) %>%
      addProviderTiles(providers$CartoDB.PositronNoLabels) %>%
      addCircleMarkers(lat = ~lat, lng = ~lon, color=~typePal(Type),
                       radius=rad, fillOpacity=0.3) %>%
      addLegend(pal=typePal, values=~Type, title="")
    
    # Create map for each system
    sys_map <- leaflet(data %>% filter(System==sys), options = leafletOptions(zoomControl = FALSE)) %>%
      addProviderTiles(providers$CartoDB.PositronNoLabels) %>%
      addCircleMarkers(lat = ~lat, lng = ~lon, color=~typePal(Type),
                       radius=rad, fillOpacity=0.3) %>%
      addLegend(pal=typePal, values=~Type, title="")
    
    # Save as .png
    mapshot(map2, file = typeMap_out)
    mapshot(sys_map, file = sysMap_out)
    
    # draw with ggplot
    p2 <- ggdraw() + draw_image(typeMap_out, scale = 1)
    p3 <- ggdraw() + draw_image(sysMap_out, scale = 1)
    
  }
  
  # save file as png
  mapshot(map, file = map_out)
  
  # draw .png with ggplot
  p1 <- ggdraw() + draw_image(map_out, scale = 1)
  
  if(output=="all"){
    return(p1)
  } else if(output=="wq_types"){
    return(p2)
  } else if(output=="sys_map"){
    return(p3)
  }
}

plot_files <- list.files("output/Figures/", full.names = TRUE)

sav_plots <- function(sys, plot_files, plot_type){
  sys_abrev <- gsub(" ", "_", sys)
  sys_files <- str_subset(plot_files, sys_abrev)
  plot <- readRDS(str_subset(sys_files, plot_type))
  return(plot)
}

```


```{r intro_snippet, results='asis'}

# Intro snippet containing funding statement
cat(knitr::knit_child('snippets/funding.Rmd', quiet=TRUE))
cat("  \n")

# Snippet containing process for BBSAP
cat(knitr::knit_child('snippets/BBSAP_process.Rmd', quiet=TRUE))
cat("  \n")

```


```{r maps, fig.height=9, fig.width=10, results='asis', eval=TRUE}
# WQ MAP
cat("  \n")
cat("\\newpage")
cat("# Maps")
cat("  \n")
cat("## Water Quality Discrete - Sample Locations - All Parameters")
cat("  \n")
subchunkify(
  print(sav_maps_list[["all_sys_map"]]),
  8,8
)

# Type maps (Estuary vs River)
cat("  \n")
cat("\\newpage")
cat("  \n")
cat("## Water Quality Discrete - Sample Locations - Estuary and River Delineations")
cat("  \n")
subchunkify(
  print(sav_maps_list[["all_sys_type_map"]]),
  8,8
)

cat("  \n")

# SAV MAP
cat("  \n")
cat("\\newpage")
cat("  \n")
cat("## Submerged Aquatic Vegetation - Sample Locations")
cat("  \n")
subchunkify(
  print(sav_maps_list[["all_sys_sav_map"]]),
  8,8
)

cat("  \n")

```

```{r system_plots, fig.height=9, fig.width=10, results='asis'}

# for(sys in unique(wq_data$System)[1:3]){
for(sys in unique(wq_data$System)){
  cat("  \n")
  cat("\\newpage")
  cat("  \n")
  sys_subtitle <- glue("# {sys}")
  cat(sys_subtitle, "\n\n")
  cat("  \n")
  subchunkify(
    print(sav_maps_list[["wq_sys_maps"]][[sys]]),
    8,8
  )
  
  cat("  \n")
  
  # SKT Results
  # Filter by system and display desired columns
  system_overview <- skt_data_combined %>%
    filter(System==sys) %>%
    mutate("Period-of-Record" = paste0(EarliestYear, " - ", LatestYear)) %>%
    select("Type", "ParameterName", "Period-of-Record", "N_Years", "N_Data", 
           "SufficientData", "SennSlope", "SennIntercept", "p", "Trend")
  
  
  # Convert "_" to "-" in column names to prevent LaTeX error
  names(system_overview) <- gsub("_","-", names(system_overview))
    
  # Conditional logic to print "large trend" statement
  lg_trend_statement <- ifelse(
    2 %in% abs(system_overview$Trend[!is.na(system_overview$Trend)]),
    TRUE,FALSE)
    
  # Add arrows only, make ParamName blue as well
  system_overview <- system_overview %>%
    mutate(Trend = ifelse(
      Trend==2, colorize("$\\Uparrow$","blue"), 
      ifelse(Trend==1, "$\\Uparrow$", 
             ifelse(Trend==-2, colorize("$\\Downarrow$","blue"), 
                    ifelse(Trend==-1, "$\\Downarrow$", Trend)))))
  
  # Description before table
  cat("  \n")
  cat(paste0("Plots will be produced below for all parameters. 
             A Seasonal Kendall-Tau trendline will be plotted only for parameters where *SufficientData* is **TRUE**."))
  cat("  \n")
  cat("  \n")
  cat(paste0("Trend arrows denote trends where the p value is less than 0.05 and the slope is less than 10% of the
              median parameter value."))
  cat("  \n")
  cat("  \n")
  # Print large trend statement for necessary systems only
  if(lg_trend_statement==TRUE){
    cat(paste0(sys," contains a *large trend*. Trends marked in ", 
               colorize("$\\Uparrow$", "blue")," or ", 
               colorize("$\\Downarrow$", "blue"), 
               " are deemed *large* trends, meaning the p value is less than 0.05 
             and the slope is greater than 10% of the median value."))
    cat("  \n")    
  }

  # Display table
  print(make_kable(system_overview %>% arrange(ParameterName),
                   paste0("Seasonal Kendall-Tau Results for ", sys),
                   format = "latex"))
  
  cat("  \n")
  cat("  \n")
  
  # Table containing program information
  print(kbl(prog_data[System==sys, -c("System", "ProgramName")],
      format="latex", 
      caption=paste0("Overview of Program Data for ", sys),
      escape=F,digits=2,vline = "",linesep = "",longtable = T,booktabs = T) %>%
    kable_styling(latex_options = c("scale_down","HOLD_position",
                                    "striped"),
                  position = "center",
                  font_size = 7) %>%
    row_spec(0, italic = TRUE))
  
  cat("  \n")
  # program names listed below (accounting for long names)
  program_ids <- sort(prog_data[System==sys, unique(ProgramID)])
  cat("\n **Program names:** \n \n")
  # Display ProgramName below data table
  for(p_id in program_ids) {
    p_name <- prog_data[System==sys & ProgramID==p_id, unique(ProgramName)]
    cat(paste0("*",p_id,"*", " - ",p_name, " - ", knitcitations::citep(bib[[paste0("SEACARID", p_id)]]), "  \n"))
  }
  
  cat("  \n")
  
  # Display skt plots for each parameter
  # for(param in c("Water Temperature","Dissolved Oxygen")){
  for(param in unique(data_combined[System==sys, ParameterName])){
    
    cat("  \n")
    cat("  \n")
    
    # Load in modified/analysed discrete data
    data <- data_directory[["data_analysis"]][[param]]
    # Getting units for each parameter
    unit <- unique(data$ParameterUnits)
    
    # defining labels for y-axis
    y_labels <- ifelse(param=="pH", paste0("Monthly average ", param), paste0("Monthly average ", param, " (",unit,")"))
    
    # Setting depth and activity values
    depth <- ifelse(param=="Secchi Depth", "Surface", "All")
    
    if(param %in% lab_params){
      activity <- "Lab"
    } else if(param %in% field_params){
      activity <- "Field"
    } else if(param %in% combined_params){
      activity <- "All"
    }
    
    # Setting Depth & Activity labels
    activity_label <- ifelse(activity=="All", "Lab and Field Combined", activity)
    depth_label <- ifelse(depth=="All", "All Depths", "Surface")
    
    ## Begin Plotting Discrete WQ ##
    cat("    \n")
    param_subtitle <- glue("## {param}")
    cat(param_subtitle, "\n\n")
    cat("  \n")
    
    subchunkify(
      plot_trendlines(sys, param, activity_label, depth_label, y_labels),
      7,11
    )
    cat("  \n")
  }
  
  # Include SAV only in Systems with SAV data
  if(sys %in% unique(SAV4$System)){
    cat("  \n")
    cat("## Submerged Aquatic Vegetation")
    cat("  \n")
    
    # Display maps for each system
    subchunkify(
      print(sav_maps_list[["sav_sys_maps"]][[sys]]),
      8,8
    )
    
    cat("  \n")
    # Display overview of Program data and collection method
    for(p_id in SAV4[System==sys, unique(ProgramID)]){
      # Grab program name, make caption for table
      p_name <- SAV4[ProgramID==p_id, unique(ProgramName)]
      caption <- paste0(p_name, " - *Program ", p_id,"*", knitcitations::citep(bib[[paste0("SEACARID",p_id)]]))
      # Subset data for each system and ProgramID
      ma_sav <- SAV4 %>% filter(System==sys, ProgramID==p_id) %>% 
        group_by(method) %>% 
        summarise(N_Data = n(),
                  YearMin = min(Year),
                  YearMax = max(Year),
                  "Sample Locations" = length(unique(ProgramLocationID))) %>%
        select(N_Data, YearMin, YearMax, method, "Sample Locations") %>%
        kable(format="simple", caption=caption, 
              col.names = c("*N_Data*","*YearMin*","*YearMax*",
                            "*Collection Method*","*Sample Locations*")) %>%
        kable_styling()
      # Exception to add a note about ProgramLocationID discrepancy b/t maps and tables
      if(p_id==559){
        ma_sav <- ma_sav %>% 
          add_footnote(glue("{p_name} - Program {p_id} contains ProgramLocationID values with Year-based suffixes. 
                            Any discrepancy between the number of Sample Locations in the table above and those 
                            portrayed on the map are due to this naming convention."))
      }
      # Display table
      print(ma_sav)
    }
    
    # Display SAV plots for a given System
    # Three plot types, select which to include
    plot_types <- c("trendplot","barplot") # don't display multiplot
    # plot_types <- c("multiplot","trendplot","barplot")

    for(plot_type in plot_types){
      # Set report subtitles
      if(plot_type == "multiplot"){
        subtitle <- "### Median Percent Cover - Species Trends"
      } else if(plot_type=="trendplot"){
        subtitle <- "### Median Percent Cover - Species Trend Table"
      } else if(plot_type=="barplot"){
        subtitle <- "### Frequency of Occurrence"
      }
      
      cat("  \n")
      cat(subtitle, "\n\n")
      cat("  \n")
      subchunkify(
        print(sav_plots(sys, plot_files, plot_type))
      )
      cat("  \n")
      if(plot_type=="trendplot"){
        sav_trend_table(sys)
        cat("  \n")
      }
    }
    cat("  \n")
  }
  cat("  \n")
}

```


```{r SAV_plots_all_systems, results='asis', fig.height=9, fig.width=10}
cat("  \n")
cat("\\newpage")
cat("  \n")
cat("# Submerged Aquatic Vegetation - Generalized Additive Models")
cat("  \n")
cat("Models generated for all systems")
cat("  \n")
save_display_gam("print")
cat("  \n")
```


```{r files_used, results='asis'}

cat("\\newpage")
cat("  \n")
cat("# SEACAR Files used in the analysis")
cat("  \n")
cat("The following files were used in the analysis: \n\n")
for(file in wq_files){
  cat(paste0("* *", tail(str_split(file, "/")[[1]],1), "*\n"))
  cat("  \n")
}
cat("  \n")
cat("Threshold file used in QA process: \n\n")
cat(paste0("* ", "[Database_Thresholds_20250409.xlsx](https://github.com/FloridaSEACAR/IndicatorQuantiles/blob/main/output/ScriptResults/Database_Thresholds_20250409.xlsx)"))

cat("  \n")
cat("  \n")

```


```{r bibliography, echo=FALSE, message=FALSE, results='asis'}
cat("\\newpage")
cat("# References")
cat("  \n")

write.bibtex(file = "SEACAR DDI citations2.bib", append=FALSE, biblatex=TRUE)
# bibliography("html")
# print(nocite_refs)

```