---
title: "Managed Area Reports - Directory"
author: "SEACAR"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Find match function
find_exact_matches <- function(pattern, filenames) {
  regex <- paste0("(_|^)", pattern, "(_|$)")
  matched_files <- str_subset(filenames, regex)
  return(matched_files)
}

MA_All <- fread("data/ManagedArea.csv", sep = ",", header = TRUE, stringsAsFactors = FALSE, na.strings = "")
MA_All <- MA_All[!MA_All$AreaID==7]
```

## Managed Area Reports

Managed Area reports are available in PDF and HTML format. The GitHub Repository is located [here](https://github.com/FloridaSEACAR/SEACAR_Trend_Analyses/tree/main/MA%20Report%20Generation).


```{r ma_list, echo = FALSE, results='asis'}

# Returns a markdown-format hyperlink, target=_blank to open link in new window
# make_link <- function(text, link){return(paste0("[",text,"](",link,")",'{:target="_blank"}'))}
make_link <- function(text, link){return(paste0('<a href="', link, '" target="_blank">',text,'</a>'))}

pdf_files <- list.files("output/Reports/PDF", pattern=".pdf")
html_files <- list.files("output/Reports/HTML", pattern=".html")

links_table <- data.frame()

for(ma in MA_All$ManagedAreaName){
  ma_abrev <- MA_All[ManagedAreaName==ma, Abbreviation]
  if(ma == "St. Joseph Bay State Buffer Preserve"){next}
  
  pdf_file <- find_exact_matches(ma_abrev, pdf_files)
  html_file <- find_exact_matches(ma_abrev, html_files)
  
  pdf_github_loc <- "https://floridaseacar.github.io/SEACAR_Trend_Analyses/MA%20Report%20Generation/output/Reports/PDF/"
  pdf_link <- paste0(pdf_github_loc, pdf_file)
  
  html_github_loc <- "https://floridaseacar.github.io/SEACAR_Trend_Analyses/MA%20Report%20Generation/output/Reports/HTML/"
  html_link <- paste0(html_github_loc, html_file)
  
  if(length(pdf_file)==0){pdf_file <- ""}
  if(length(html_file)==0){html_file <- ""}
  
  link_table <- data.frame("Managed Area" = ma,
                           "PDF" = make_link(pdf_file, pdf_link),
                           "HTML" = make_link(html_file, html_link))
  
  links_table <- bind_rows(links_table, link_table)
}

print(
  kable(links_table, format = "simple", table.attr = "style='width:30%;'")
)

```

The reports were last ran on **`r format(Sys.Date(), '%m/%d/%Y')`** using the following export files:

```{r file_list, echo = FALSE, results='asis'}

cat("  \n")
cat("**Discrete WQ**:  \n\n")
for(file in wq_discrete_files){
  cat(paste0("* *", file, "*\n"))
  cat("  \n")
}

cat("  \n")
cat("**Continuous WQ**:  \n\n")
for (param in cont_params_long){
  p <- str_replace_all(param, " ", "_")
  par_reg <- paste0(p, "_", region)
  
  file_name <- str_subset(wq_cont_files_short, par_reg)
  
  cat(paste0("* *", file_name, "*\n"))
  cat("  \n")
}

cat("  \n")
cat("**Submerged Aquatic Vegetation**:  \n\n")
cat(paste0("* *", sav_file_short,"*"))
cat("  \n")

cat("  \n")
cat("**Nekton**:  \n\n")
cat(paste0("* *", nekton_file_short,"*"))
cat("  \n")

cat("  \n")
cat("**Coral**:  \n\n")
cat(paste0("* *", coral_file_short,"*"))
cat("  \n")

cat("  \n")
cat("**Coastal Wetlands**:  \n\n")
cat(paste0("* *", cw_file_short,"*"))
cat("  \n")

cat("  \n")
cat("**Coastal Wetlands**:  \n\n")
cat(paste0("* *", cw_file_short,"*"))
cat("  \n")

cat("  \n")
cat("**Oyster**:  \n\n")
cat(paste0("* *", oyster_file_short,"*"))
cat("  \n")

```

```{r funding snippet, results='asis', echo=FALSE}
# Intro snippet containing funding statement
cat("  \n")
cat(knitr::knit_child('snippets/funding.Rmd', quiet=TRUE))
cat("  \n")
```