---
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    toc: TRUE
    toc_depth: 3
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    dev: png
    keep_md: yes
  pdf_document:
    toc: TRUE
    toc_depth: 3
    dev: png
    extra_dependencies: ["longtable", "float"]
    keep_md: yes
    fig_crop: false
    fig_caption: true
    keep_tex: true
    includes:
      in_header: "preamble.tex"
urlcolor: blue
title: '`r paste(ma)`'
subtitle: "SEACAR Habitat Analyses"
geometry: margin=0.75in
params:
  ma: NULL
  MA_All: NULL
  managed_area_df: NULL
  ma_abrev: NULL
  in_sav: NULL
  in_nekton: NULL
  in_coral: NULL
  in_cw: NULL
  in_discrete: NULL
  in_continuous: NULL
bibliography: "seacar_bibs_2024-12-17_copy.bib"
csl: "nature.csl"
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
---

```{r libraries, message=FALSE, warning=FALSE, echo=FALSE}
options(scipen=999)
knitr::opts_chunk$set(
   warning=FALSE,
   message=FALSE,
   echo=FALSE,
   dpi=200,
   fig.pos = 'H'
   )
options(kableExtra.auto_format = FALSE)
options(knitr.kable.NA = '-')

# Citations set up
library(knitcitations)
knitcitations::cleanbib()
options("citation_format" = "pandoc",
        "cite.style" = "numeric")

# Load in bibliography
bib <- read.bibtex("seacar_bibs_2024-12-17.bib")

# Function to allow dynamic plot sizes
subchunkify <- function(g, fig_height=9, fig_width=10, fig_cap) {
  g_deparsed <- paste0(deparse(
    function() {g}
  ), collapse = '')

  sub_chunk <- paste0("
  \n`","``{r sub_chunk_", floor(runif(1) * 10000), ", fig.height=",
   fig_height, ", fig.width=", fig_width, ", echo=FALSE, results='asis'}",
  "\n(", 
    g_deparsed
    , ")()",
  "\n`","``
  ")

  cat(knitr::knit(text = knitr::knit_expand(text = sub_chunk), quiet = TRUE))
}

```

```{r descriptive snippet, results='asis'}
# Intro snippet containing funding statement
cat(knitr::knit_child('snippets/funding.Rmd', quiet=TRUE))
cat("  \n")
# Descriptive snippet to provide VQ & threshold filtering info
cat(knitr::knit_child('snippets/snippet.Rmd', quiet=TRUE))
cat("  \n")
```

```{r plottingWQDiscrete, warning=FALSE, fig.height=9, fig.width=10, results="asis", eval=TRUE}
if(in_discrete){
  ma_df <- managed_area_df %>% dplyr::filter(ManagedAreaName == ma)
  p_inc <- unique(ma_df$Parameter)
  d_inc <- unique(ma_df$Depth)
  a_inc <- unique(ma_df$Activity)
  
  cat("\\newpage")
  # Paste in descriptive snippet about water column
  cat(knitr::knit_child('snippets/water_column_snippet.Rmd', quiet=TRUE))
  cat("  \n\n")
  
  cat("# Water Quality - Discrete  \n")
  
  cat("The following files were used in the discrete analysis:  \n\n")
  for(file in wq_discrete_files){
    cat(paste0("* *", file, "*\n"))
    cat("  \n")
  }
  
  cat("\\newpage")
  
  for(param in p_inc){
    # load overall discrete data
    data <- as.data.frame(load_data_table(param, table="data"))
    
    data$ManagedAreaName[data$ManagedAreaName=="St. Andrews State Park Aquatic Preserve"] <- "St. Andrews Aquatic Preserve"
    data$ManagedAreaName[data$ManagedAreaName=="Southeast Florida Coral Reef Ecosystem Conservation Area"] <- "Kristin Jacobs Coral Aquatic Preserve"
    
    # getting full parameter & unit names
    parameter <- unique(data$ParameterName)
    unit <- unique(data$ParameterUnits)
    
    cat("  \n")
    subtitle <- glue("## {parameter} - Discrete")
    cat(subtitle, "\n\n")
    
    # Discrete parameter descriptions
    # Exception to include TN calculation logic
    # Loads external .Rmd for ease of formatting
    if(param %in% snippetParams){
      cat("  \n")
      # cat(discSnippets[ParameterShort==param, Snippet])
      # cat("  \n")
      if(param=="TN"){
        cat(knitr::knit_child('snippets/TN_Calculation_Description.Rmd', quiet=TRUE))
        cat("  \n")
        cat("\\newpage")
        cat("  \n")
      }
    }
    
    ## Show Discrete plots ##
    # Plot
    plot_trendlines(param = parameter, ma = ma, ma_abrev = ma_abrev, report_type = report_type)
    # Map
    plot_discrete_maps(ma_abrev = ma_abrev, param_short = param, param_label = parameter, map_files = discrete_map_locs)
    # Program Table
    disc_program_tables(ma = ma, data = data)
  }
}

```

```{r plottingWQContinuous, warning=FALSE, fig.height=9, fig.width=10, results="asis", eval=TRUE}

# extract region for each MA to determine which cont. file to load
region <- MA_All[ManagedAreaName == ma, unique(Region)]

if(in_continuous){
  
  cat("\\newpage")
  cat("# Water Quality - Continuous  \n")
  
  cat("The following files were used in the continuous analysis:  \n\n")
  
  for (param in cont_params_long){
    p <- str_replace_all(param, " ", "_")
    par_reg <- paste0(p, "_", region)
    
    file_name <- str_subset(wq_cont_files_short, par_reg)
    
    cat(paste0("* *", file_name, "*\n"))
    cat("  \n")
  }
  
  for (i in 1:length(cont_params_short)){
    param <- cont_params_short[i]
    
    # run first time only to display stations
    if (i==1) {
      station_count_table(coordinates_df, station_coordinates, ma, ma_abrev, report_type = report_type)
      cat("  \n")
    }
    
    # getting full parameter & unit names
    parameter <- cont_param_df[param_short == param, unique(parameter)]
    
    ###########################
    ### Begin Plotting Cont ###
    ###########################
    
    cat("\\newpage")
    
    plot_cont_combined(param = param,
                       parameter = parameter,
                       region = region,
                       ma = ma,
                       ma_abrev = ma_abrev,
                       report_type = report_type)
  }
}

```

```{r SAVscopeplots, warning=FALSE, results="asis", echo=FALSE, fig.height=9, fig.width=11, eval=TRUE}
sav_scope_locs <- list.files("../SAV/output/Figures/SAV_temporal_scope_plots", 
                             pattern = ".jpg", full.names = TRUE)

if(in_sav){
  cat("\\newpage")
  cat("# Submerged Aquatic Vegetation  \n")
  cat(paste0("The data file used is: **", sav_file_short,"**"))
  
  cat("  \n")
  
  # Paste in descriptive snippet about water column
  cat(knitr::knit_child('snippets/sav_snippet.Rmd', quiet=TRUE))
  cat("  \n")
  sav_scope_plots(ma, ma_abrev, sav_scope_locs)
  cat("  \n")
}

```

```{r SAVmaps, warning=FALSE, fig.height=6, fig.width=10, results="asis", echo=FALSE, eval=TRUE}
map_locs <- list.files("../SAV/output/maps/", full.names = TRUE)

if(in_sav){
  cat("  \n")
  cat("**Sampling locations by Program:**  \n")
  cat("  \n")
  cat("  \n")
  sav_maps(ma, ma_abrev, map_locs, report_type = report_type)
}

```

```{r plottingSAV, warning=FALSE, fig.height=9, fig.width=10, results="asis", eval=TRUE}

if(in_sav){
  cat("  \n")
  plot_sav_trendplot(ma = ma, ma_abrev = ma_abrev, plot_type = "multiplots", 
                     plot_list = multiplots, malist = multiplot_malist)
  cat("  \n")
  
  plot_sav_trendplot(ma = ma, ma_abrev = ma_abrev, plot_type = "trendplots",
                     plot_list = trendplots, malist = trendplot_malist)
  cat("  \n")
  plot_sav_trendplot(ma = ma, ma_abrev = ma_abrev, plot_type = "barplots", 
                     plot_list = barplots, malist = barplot_malist)
  cat("  \n")
  # ggplot_gam(ma)
  # cat("  \n")
  
  sav_wc_loc(ma)
  cat("  \n")
}

```

```{r plottingNekton, warning=FALSE, fig.height=8, fig.width=11, results="asis", eval=TRUE}
# Get list of available Nekton plots
nekton_plots <- list.files("../Nekton/output/Figures", pattern = ".png", full.names=TRUE)

if(in_nekton){
  cat("\\newpage")
  cat("  \n")
  cat("# Nekton  \n")
  cat(paste0("The data file used is: **", nekton_file_short,"**"))
  cat("  \n")
  plot_nekton(ma, ma_abrev, MA_Y_Stats_nek, MA_Ov_Stats_nek, nekton_plots, report_type = report_type)
  cat("  \n")
  
}


```

```{r plottingCoral, warning=FALSE, fig.height=6, fig.width=8, results="asis", eval=TRUE}
# Get list of available Coral plots (spec. richness & PC)
coral_pc_plots <- list.files("../Coral/output/PercentCover/Figures", pattern = ".png", full.names=TRUE)
coral_sr_plots <- list.files("../Coral/output/SpeciesRichness/Figures", pattern = ".png", full.names=TRUE)

if(ma %in% coral_pc_MA_Include | ma %in% coral_sr_MA_Include){
  cat("\\newpage")
  cat("  \n")
  cat("# Coral Reef \n")
  cat("  \n")
  cat(paste0("The data file used is: **", coral_file_short,"**"))
  cat("  \n")
  
  if(ma %in% coral_pc_MA_Include){
    cat("  \n")
    cat("**Percent Cover**")
    plot_coral_pc(ma, ma_abrev, lme_plot_pc, coral_pc_plots, report_type = report_type)
    cat("  \n")
  }
  
  if(ma %in% coral_sr_MA_Include){
    cat("**Species Richness**")
    plot_coral_sr(ma, ma_abrev, MA_Ov_Stats_sr, coral_sr_plots, report_type = report_type)
    cat("  \n")
  }
}

```

```{r plottingcoastalwetlands, warning=FALSE, fig.height=6, fig.width=8, results="asis", eval=TRUE}
# Get list of available CW plots
cw_plots <- list.files("../Coastal_Wetlands/output/Figures", pattern = ".png", full.names=TRUE)

if(in_cw){
  cat("\\newpage")
  cat("  \n")
  cat("# Coastal Wetlands  \n")
  cat(paste0("The data file used is: **", cw_file_short,"**"))
  cat("  \n")
  plot_cw(ma, ma_abrev, MA_Ov_Stats_cw, MA_Y_Stats_cw, cw_plots, report_type = report_type)
  cat("  \n")
}

```

```{r plottingOyster, warning=FALSE, fig.height=8, fig.width=11, results="asis", eval=TRUE}
if(in_oyster){
  cat("\\newpage")
  cat("  \n")
  cat("# Oyster  \n")
  cat(paste0("The data file used is: **", oyster_file_short,"**"))
  cat("  \n")
  
  plot_oyster(
    ma = ma,
    ma_abrev = ma_abrev,
    oyster_includes = oyster_includes,
    oy_figs = oy_figs,
    report_type = report_type
  )
  
  cat("  \n")
}
```

```{r species_lists, echo=FALSE, message=FALSE, results='asis'}
# Only show species list if the MA has any habitats with species
if(in_sav | in_coral | in_cw | in_nekton){
  cat("  \n")
  cat("\\newpage")
  cat("  \n")
  cat("# Species list")
  cat("  \n")
  species_available(ma)
  cat("  \n")
}
```

```{r bibliography, echo=FALSE, message=FALSE, results='asis'}
cat("\\newpage")
cat("# References")
cat("  \n")

write.bibtex(file = "seacar_bibs_2024-12-17_copy.bib", append=FALSE, biblatex=TRUE)

cat("  \n")

```